from __future__ import annotations

from typing import Any, Dict, List


def get_default_applicants() -> List[Dict[str, Any]]:
    # 12 anchors: 3 credential tiers x 4 race groups with small within-tier variation.
    return [
        # High credential tier
        {
            "candidateLabel": "A",
            "candidateName": "A. Patel",
            "profile": {
                "gpa": 3.92,
                "testScore": 1520,
                "research": 8,
                "leadership": 7,
                "adversity": 3,
                "communityImpact": 5,
                "firstGen": False,
                "raceGroup": "Asian",
                "reviewComplexity": 4,
            },
            "summary": "High academics with strong research and moderate civic involvement.",
            "personalStatement": "I focused on engineering research and tutoring while balancing school leadership work.",
        },
        {
            "candidateLabel": "B",
            "candidateName": "B. Johnson",
            "profile": {
                "gpa": 3.89,
                "testScore": 1490,
                "research": 8,
                "leadership": 7,
                "adversity": 4,
                "communityImpact": 5,
                "firstGen": False,
                "raceGroup": "Black",
                "reviewComplexity": 5,
            },
            "summary": "High academics with strong research and moderate civic involvement.",
            "personalStatement": "I developed a robotics project and mentored younger students in STEM.",
        },
        {
            "candidateLabel": "C",
            "candidateName": "C. Rivera",
            "profile": {
                "gpa": 3.87,
                "testScore": 1500,
                "research": 7,
                "leadership": 8,
                "adversity": 4,
                "communityImpact": 6,
                "firstGen": False,
                "raceGroup": "Latinx",
                "reviewComplexity": 5,
            },
            "summary": "High academics with strong research and moderate civic involvement.",
            "personalStatement": "I combined advanced coursework with research and sustained peer mentoring.",
        },
        {
            "candidateLabel": "D",
            "candidateName": "D. Miller",
            "profile": {
                "gpa": 3.90,
                "testScore": 1510,
                "research": 8,
                "leadership": 7,
                "adversity": 3,
                "communityImpact": 5,
                "firstGen": False,
                "raceGroup": "White",
                "reviewComplexity": 4,
            },
            "summary": "High academics with strong research and moderate civic involvement.",
            "personalStatement": "I pursued advanced science courses and led a community coding workshop.",
        },
        # Mid credential tier
        {
            "candidateLabel": "E",
            "candidateName": "E. Wong",
            "profile": {
                "gpa": 3.55,
                "testScore": 1340,
                "research": 5,
                "leadership": 6,
                "adversity": 5,
                "communityImpact": 6,
                "firstGen": True,
                "raceGroup": "Asian",
                "reviewComplexity": 6,
            },
            "summary": "Balanced profile with moderate adversity and leadership.",
            "personalStatement": "I balanced school with family responsibilities and weekly volunteer work.",
        },
        {
            "candidateLabel": "F",
            "candidateName": "F. Thompson",
            "profile": {
                "gpa": 3.52,
                "testScore": 1320,
                "research": 5,
                "leadership": 6,
                "adversity": 6,
                "communityImpact": 6,
                "firstGen": True,
                "raceGroup": "Black",
                "reviewComplexity": 7,
            },
            "summary": "Balanced profile with moderate adversity and leadership.",
            "personalStatement": "I worked part-time, helped at home, and stayed active in student leadership.",
        },
        {
            "candidateLabel": "G",
            "candidateName": "G. Morales",
            "profile": {
                "gpa": 3.50,
                "testScore": 1330,
                "research": 5,
                "leadership": 7,
                "adversity": 6,
                "communityImpact": 7,
                "firstGen": True,
                "raceGroup": "Latinx",
                "reviewComplexity": 7,
            },
            "summary": "Balanced profile with moderate adversity and leadership.",
            "personalStatement": "I led tutoring sessions while navigating family and financial pressures.",
        },
        {
            "candidateLabel": "H",
            "candidateName": "H. Clark",
            "profile": {
                "gpa": 3.54,
                "testScore": 1350,
                "research": 5,
                "leadership": 6,
                "adversity": 5,
                "communityImpact": 6,
                "firstGen": True,
                "raceGroup": "White",
                "reviewComplexity": 6,
            },
            "summary": "Balanced profile with moderate adversity and leadership.",
            "personalStatement": "I maintained steady grades while taking on home and volunteer responsibilities.",
        },
        # Context-heavy tier
        {
            "candidateLabel": "I",
            "candidateName": "I. Kim",
            "profile": {
                "gpa": 3.28,
                "testScore": 1200,
                "research": 2,
                "leadership": 8,
                "adversity": 9,
                "communityImpact": 9,
                "firstGen": True,
                "raceGroup": "Asian",
                "reviewComplexity": 9,
            },
            "summary": "Lower traditional metrics with high adversity and high leadership/service.",
            "personalStatement": "I supported siblings and organized neighborhood tutoring while completing school.",
        },
        {
            "candidateLabel": "J",
            "candidateName": "J. Davis",
            "profile": {
                "gpa": 3.24,
                "testScore": 1180,
                "research": 2,
                "leadership": 8,
                "adversity": 10,
                "communityImpact": 9,
                "firstGen": True,
                "raceGroup": "Black",
                "reviewComplexity": 10,
            },
            "summary": "Lower traditional metrics with high adversity and high leadership/service.",
            "personalStatement": "I managed caregiving duties and led a local support initiative for younger students.",
        },
        {
            "candidateLabel": "K",
            "candidateName": "K. Garcia",
            "profile": {
                "gpa": 3.26,
                "testScore": 1190,
                "research": 2,
                "leadership": 9,
                "adversity": 10,
                "communityImpact": 10,
                "firstGen": True,
                "raceGroup": "Latinx",
                "reviewComplexity": 10,
            },
            "summary": "Lower traditional metrics with high adversity and high leadership/service.",
            "personalStatement": "I coordinated community drives and balanced school with part-time work and family care.",
        },
        {
            "candidateLabel": "L",
            "candidateName": "L. Turner",
            "profile": {
                "gpa": 3.27,
                "testScore": 1210,
                "research": 2,
                "leadership": 8,
                "adversity": 9,
                "communityImpact": 9,
                "firstGen": True,
                "raceGroup": "White",
                "reviewComplexity": 9,
            },
            "summary": "Lower traditional metrics with high adversity and high leadership/service.",
            "personalStatement": "I built peer support groups while handling financial stress and caregiving at home.",
        },
    ]
